#!/bin/sh /etc/rc.common
# Openwrt-wan-keep-alive initscript
# Copyright (C) 2007 OpenWrt.org

START=99
STOP=15
PIDFILE=/var/pids/wan-keep-alive.pid
PIDDIR=/var/pids
CONFIG_FILE=/usr/openwrt-wan-keep-alive/owka.conf

if [ -f "$CONFIG_FILE" ]; then
	. "$CONFIG_FILE"
fi

# BINFILE is taken from config if present, else default install path
BINFILE="${OWKA_INSTALL_DIR:-/usr/openwrt-wan-keep-alive}/wan-keep-alive.sh"

start() {
	[ -d $PIDDIR ] || mkdir -p $PIDDIR
	[ -f $PIDFILE ] && exit 1
	"$BINFILE" 2>&1 >/dev/null &
	echo $! > $PIDFILE
}

stop() {
	kill `cat $PIDFILE`
	rm $PIDFILE
}
